#!/usr/bin/env python3
"""
Export the RADEv2 transmitter constants needed by the pure-C TX entrypoint.

This writes:
  - src/tx2_model_data.h
  - src/tx2_model_data.c

Exported quantities (production 250725 / latent-56 / bottleneck-3 / peak):
  - model geometry macros (M, Ncp, Ns, Nc, LATENT_DIM, Fs)
  - per-frame sizes (NMF = Nzmf*Ns*(M+Ncp), NEOO = 6*(M+Ncp))
  - carrier frequencies w[Nc]         (rad/sample; for optional TX BPF)
  - inverse DFT matrix Winv[Nc][M]    (carrier synthesis, row-major)
  - pilot_gain_eoo_v2                 (scalar)
  - eoo_v2[NEOO]                      (precomputed 6-symbol EOO waveform)

Copyright (c) 2026 Rhizomatica, BSD-3-Clause
"""

from pathlib import Path

import numpy as np

from radae import RADAE


MODEL_PATH = Path("src")
HEADER_PATH = MODEL_PATH / "tx2_model_data.h"
SOURCE_PATH = MODEL_PATH / "tx2_model_data.c"


def format_float_rows(values, per_line=8):
    items = [f"{float(v):.9e}f" for v in values]
    return ["    " + ", ".join(items[i:i + per_line]) + "," for i in range(0, len(items), per_line)]


def format_comp_rows(values, per_line=4):
    items = [f"    {{{float(v.real):.9e}f, {float(v.imag):.9e}f}}" for v in values]
    rows = []
    for i in range(0, len(items), per_line):
        rows.append(",\n".join(items[i:i + per_line]) + ",")
    return rows


def format_comp_matrix_rows(matrix, per_line=3):
    """matrix is (rows, cols) complex.  Emit as flat row-major COMP[rows*cols]."""
    flat = matrix.reshape(-1)
    return format_comp_rows(flat, per_line=per_line)


def main():
    # Same constructor the RX export uses; matches radae_txe2.py production.
    model = RADAE(
        21,
        56,
        EbNodB=100,
        Nzmf=1,
        rate_Fs=True,
        bottleneck=3,
        cyclic_prefix=0.004,
        time_offset=-16,
        correct_time_offset=-16,
        stateful_decoder=False,
        w1_dec=128,
        w1_dec_stateful=128,
        peak=True,
    )

    M   = int(model.M)
    Ncp = int(model.Ncp)
    Ns  = int(model.Ns)
    Nc  = int(model.Nc)
    Nzmf = int(model.Nzmf)
    latent_dim = int(model.latent_dim)
    Fs  = float(model.Fs)

    Nmf  = Nzmf * Ns * (M + Ncp)
    Neoo = 6 * (M + Ncp)

    w = model.w.detach().cpu().numpy().astype(np.float32)
    assert w.shape == (Nc,), w.shape

    Winv  = model.Winv.detach().cpu().numpy().astype(np.complex64)
    assert Winv.shape == (Nc, M), Winv.shape

    pilot_gain_eoo_v2 = float(model.pilot_gain_eoo_v2)
    eoo_v2 = model.eoo_v2.detach().cpu().numpy().astype(np.complex64).reshape(-1)
    assert eoo_v2.shape == (Neoo,), eoo_v2.shape

    header = f"""/* Auto generated by export_tx2_model_data.py.  DO NOT EDIT. */

#ifndef TX2_MODEL_DATA_H
#define TX2_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {{
#endif

#include "comp.h"

#define TX2_MODEL_M {M}
#define TX2_MODEL_NCP {Ncp}
#define TX2_MODEL_NS {Ns}
#define TX2_MODEL_NC {Nc}
#define TX2_MODEL_NZMF {Nzmf}
#define TX2_MODEL_LATENT_DIM {latent_dim}
#define TX2_MODEL_FS {Fs:.1f}f

#define TX2_MODEL_NMF  {Nmf}
#define TX2_MODEL_NEOO {Neoo}

/* Carrier angular frequencies (rad/sample). */
extern const float tx2_model_w[TX2_MODEL_NC];

/* Row-major [Nc][M] inverse DFT matrix used for OFDM synthesis. */
extern const COMP  tx2_model_Winv[TX2_MODEL_NC * TX2_MODEL_M];

/* Precomputed V2 end-of-over waveform (6 pend_cp symbols, scaled). */
extern const COMP  tx2_model_eoo_v2[TX2_MODEL_NEOO];

/* Gain already baked into eoo_v2; exposed for reference / tests. */
extern const float tx2_model_pilot_gain_eoo_v2;

#ifdef __cplusplus
}}
#endif

#endif /* TX2_MODEL_DATA_H */
"""

    source_lines = [
        "/* Auto generated by export_tx2_model_data.py.  DO NOT EDIT. */",
        "",
        '#include "tx2_model_data.h"',
        "",
        "const float tx2_model_w[TX2_MODEL_NC] = {",
        *format_float_rows(w, per_line=7),
        "};",
        "",
        "const COMP tx2_model_Winv[TX2_MODEL_NC * TX2_MODEL_M] = {",
        *format_comp_matrix_rows(Winv, per_line=3),
        "};",
        "",
        "const COMP tx2_model_eoo_v2[TX2_MODEL_NEOO] = {",
        *format_comp_rows(eoo_v2, per_line=3),
        "};",
        "",
        f"const float tx2_model_pilot_gain_eoo_v2 = {pilot_gain_eoo_v2:.9e}f;",
        "",
    ]

    HEADER_PATH.write_text(header)
    SOURCE_PATH.write_text("\n".join(source_lines))
    print(f"wrote {HEADER_PATH}")
    print(f"wrote {SOURCE_PATH}")
    print(f"  M={M} Ncp={Ncp} Ns={Ns} Nc={Nc} Nzmf={Nzmf} latent_dim={latent_dim}")
    print(f"  Nmf={Nmf} Neoo={Neoo}")
    print(f"  pilot_gain_eoo_v2={pilot_gain_eoo_v2:.6e}")


if __name__ == "__main__":
    main()
