#!/usr/bin/env python3
"""
Export the small RADEv2 receiver constants needed by the pure-C RX entrypoint.

This writes:
  - src/rx2_model_data.h
  - src/rx2_model_data.c

Only geometry/config arrays needed by the receiver glue are exported here:
  - carrier frequencies `w`
  - time-domain `pend` symbol
"""

from pathlib import Path

import numpy as np

from radae import RADAE


MODEL_PATH = Path("src")
HEADER_PATH = MODEL_PATH / "rx2_model_data.h"
SOURCE_PATH = MODEL_PATH / "rx2_model_data.c"


def format_float_rows(values, per_line=8):
    items = [f"{float(v):.9e}f" for v in values]
    return ["    " + ", ".join(items[i:i + per_line]) + "," for i in range(0, len(items), per_line)]


def format_comp_rows(values, per_line=4):
    items = [f"    {{{float(v.real):.9e}f, {float(v.imag):.9e}f}}" for v in values]
    rows = []
    for i in range(0, len(items), per_line):
        rows.append(",\n".join(items[i:i + per_line]) + ",")
    return rows


def main():
    model = RADAE(
        21,
        56,
        EbNodB=100,
        Nzmf=1,
        rate_Fs=True,
        bottleneck=3,
        cyclic_prefix=0.004,
        time_offset=-16,
        correct_time_offset=-16,
        stateful_decoder=False,
        w1_dec=128,
        w1_dec_stateful=128,
        peak=True,
    )

    w = model.w.detach().cpu().numpy().astype(np.float32)
    pend = model.pend.detach().cpu().numpy().astype(np.complex64)

    header = f"""/* Auto generated by export_rx2_model_data.py */

#ifndef RX2_MODEL_DATA_H
#define RX2_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {{
#endif

#include "comp.h"

#define RX2_MODEL_M {model.M}
#define RX2_MODEL_NCP {model.Ncp}
#define RX2_MODEL_NS {model.Ns}
#define RX2_MODEL_NC {model.Nc}
#define RX2_MODEL_TIME_OFFSET {model.time_offset}
#define RX2_MODEL_CORRECT_TIME_OFFSET {model.correct_time_offset}
#define RX2_MODEL_FS {float(model.Fs):.1f}f

extern const float rx2_model_w[RX2_MODEL_NC];
extern const COMP rx2_model_pend[RX2_MODEL_M];

#ifdef __cplusplus
}}
#endif

#endif /* RX2_MODEL_DATA_H */
"""

    source_lines = [
        "/* Auto generated by export_rx2_model_data.py */",
        "",
        '#include "rx2_model_data.h"',
        "",
        f"const float rx2_model_w[RX2_MODEL_NC] = {{",
        *format_float_rows(w, per_line=7),
        "};",
        "",
        f"const COMP rx2_model_pend[RX2_MODEL_M] = {{",
        *format_comp_rows(pend, per_line=3),
        "};",
        "",
    ]

    HEADER_PATH.write_text(header)
    SOURCE_PATH.write_text("\n".join(source_lines))
    print(f"wrote {HEADER_PATH}")
    print(f"wrote {SOURCE_PATH}")


if __name__ == "__main__":
    main()
