"""
Export FrameSyncNet weights from a .pth checkpoint to a C header.

FrameSyncNet (models_sync.py) is a 3-layer MLP:
    Linear(input_dim, 64) -> ReLU
    Linear(64, 64)        -> ReLU
    Linear(64, 1)         -> Sigmoid

Generated output:
    <output_dir>/frame_sync_data.h  - extern declarations + INPUT_DIM macro
    <output_dir>/frame_sync_data.c  - static const float arrays with weights

Usage:
    python3 export_frame_sync_weights.py <checkpoint.pth> <output_dir>
                                         [--input-dim 56]

Copyright (c) 2026 Rhizomatica, BSD-3-Clause
"""

import argparse
import os
import sys

import torch

from models_sync import FrameSyncNet


def write_header(out_dir, input_dim):
    """Emit frame_sync_data.h."""
    path = os.path.join(out_dir, "frame_sync_data.h")
    with open(path, "w") as f:
        f.write("/* Auto-generated by export_frame_sync_weights.py. DO NOT EDIT. */\n")
        f.write("#ifndef FRAME_SYNC_DATA_H\n")
        f.write("#define FRAME_SYNC_DATA_H\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        f.write(f"#define FRAME_SYNC_INPUT_DIM {input_dim}\n")
        f.write("#define FRAME_SYNC_HIDDEN_DIM 64\n\n")
        f.write("extern const float frame_sync_w0[FRAME_SYNC_HIDDEN_DIM][FRAME_SYNC_INPUT_DIM];\n")
        f.write("extern const float frame_sync_b0[FRAME_SYNC_HIDDEN_DIM];\n")
        f.write("extern const float frame_sync_w2[FRAME_SYNC_HIDDEN_DIM][FRAME_SYNC_HIDDEN_DIM];\n")
        f.write("extern const float frame_sync_b2[FRAME_SYNC_HIDDEN_DIM];\n")
        f.write("extern const float frame_sync_w4[FRAME_SYNC_HIDDEN_DIM];\n")
        f.write("extern const float frame_sync_b4;\n\n")
        f.write("#ifdef __cplusplus\n}\n#endif\n\n")
        f.write("#endif /* FRAME_SYNC_DATA_H */\n")
    return path


def _format_array(name, arr, per_line=8):
    """Emit `static const float NAME[...] = { ... };` as a string."""
    shape = arr.shape
    if len(shape) == 1:
        head = f"const float {name}[{shape[0]}] = {{\n"
    elif len(shape) == 2:
        head = f"const float {name}[{shape[0]}][{shape[1]}] = {{\n"
    else:
        raise ValueError(f"unexpected shape {shape} for {name}")

    flat = arr.reshape(-1)
    rows = []
    for i, v in enumerate(flat):
        rows.append(f"{v:.9e}f")
    lines = []
    for i in range(0, len(rows), per_line):
        lines.append("    " + ", ".join(rows[i:i + per_line]) + ",")
    body = "\n".join(lines).rstrip(",")
    return head + body + "\n};\n"


def write_source(out_dir, sd, input_dim):
    """Emit frame_sync_data.c."""
    w0 = sd["linear_stack.0.weight"].detach().cpu().numpy()   # [64, input_dim]
    b0 = sd["linear_stack.0.bias"].detach().cpu().numpy()     # [64]
    w2 = sd["linear_stack.2.weight"].detach().cpu().numpy()   # [64, 64]
    b2 = sd["linear_stack.2.bias"].detach().cpu().numpy()     # [64]
    w4 = sd["linear_stack.4.weight"].detach().cpu().numpy()   # [1, 64]
    b4 = sd["linear_stack.4.bias"].detach().cpu().numpy()     # [1]

    assert w0.shape == (64, input_dim), w0.shape
    assert b0.shape == (64,), b0.shape
    assert w2.shape == (64, 64), w2.shape
    assert b2.shape == (64,), b2.shape
    assert w4.shape == (1, 64), w4.shape
    assert b4.shape == (1,), b4.shape

    path = os.path.join(out_dir, "frame_sync_data.c")
    with open(path, "w") as f:
        f.write("/* Auto-generated by export_frame_sync_weights.py. DO NOT EDIT. */\n")
        f.write("#include \"frame_sync_data.h\"\n\n")
        f.write(_format_array("frame_sync_w0", w0))
        f.write("\n")
        f.write(_format_array("frame_sync_b0", b0))
        f.write("\n")
        f.write(_format_array("frame_sync_w2", w2))
        f.write("\n")
        f.write(_format_array("frame_sync_b2", b2))
        f.write("\n")
        f.write(_format_array("frame_sync_w4", w4.reshape(-1)))
        f.write("\n")
        f.write(f"const float frame_sync_b4 = {b4[0]:.9e}f;\n")
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("checkpoint", type=str, help="fsync .pth checkpoint")
    parser.add_argument("output_dir", type=str, help="output directory")
    parser.add_argument("--input-dim", type=int, default=56,
                        help="latent_dim of parent RADAE model (default 56)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    sd = torch.load(args.checkpoint, map_location="cpu")

    # Instantiate and load strictly so we catch any architecture drift.
    net = FrameSyncNet(args.input_dim)
    net.load_state_dict(sd, strict=True)

    hpath = write_header(args.output_dir, args.input_dim)
    cpath = write_source(args.output_dir, sd, args.input_dim)
    print(f"wrote {hpath}")
    print(f"wrote {cpath}")


if __name__ == "__main__":
    sys.exit(main())
