/* Auto-generated by export_frame_sync_weights.py. DO NOT EDIT. */
#ifndef FRAME_SYNC_DATA_H
#define FRAME_SYNC_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#define FRAME_SYNC_INPUT_DIM 56
#define FRAME_SYNC_HIDDEN_DIM 64

extern const float frame_sync_w0[FRAME_SYNC_HIDDEN_DIM][FRAME_SYNC_INPUT_DIM];
extern const float frame_sync_b0[FRAME_SYNC_HIDDEN_DIM];
extern const float frame_sync_w2[FRAME_SYNC_HIDDEN_DIM][FRAME_SYNC_HIDDEN_DIM];
extern const float frame_sync_b2[FRAME_SYNC_HIDDEN_DIM];
extern const float frame_sync_w4[FRAME_SYNC_HIDDEN_DIM];
extern const float frame_sync_b4;

#ifdef __cplusplus
}
#endif

#endif /* FRAME_SYNC_DATA_H */
