/* Auto generated by export_rx2_model_data.py */

#ifndef RX2_MODEL_DATA_H
#define RX2_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "comp.h"

#define RX2_MODEL_M 128
#define RX2_MODEL_NCP 32
#define RX2_MODEL_NS 2
#define RX2_MODEL_NC 14
#define RX2_MODEL_TIME_OFFSET -16
#define RX2_MODEL_CORRECT_TIME_OFFSET -16
#define RX2_MODEL_FS 8000.0f

extern const float rx2_model_w[RX2_MODEL_NC];
extern const COMP rx2_model_pend[RX2_MODEL_M];

#ifdef __cplusplus
}
#endif

#endif /* RX2_MODEL_DATA_H */
