/* Auto generated by export_tx2_model_data.py.  DO NOT EDIT. */

#ifndef TX2_MODEL_DATA_H
#define TX2_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "comp.h"

#define TX2_MODEL_M 128
#define TX2_MODEL_NCP 32
#define TX2_MODEL_NS 2
#define TX2_MODEL_NC 14
#define TX2_MODEL_NZMF 1
#define TX2_MODEL_LATENT_DIM 56
#define TX2_MODEL_FS 8000.0f

#define TX2_MODEL_NMF  320
#define TX2_MODEL_NEOO 960

/* Carrier angular frequencies (rad/sample). */
extern const float tx2_model_w[TX2_MODEL_NC];

/* Row-major [Nc][M] inverse DFT matrix used for OFDM synthesis. */
extern const COMP  tx2_model_Winv[TX2_MODEL_NC * TX2_MODEL_M];

/* Precomputed V2 end-of-over waveform (6 pend_cp symbols, scaled). */
extern const COMP  tx2_model_eoo_v2[TX2_MODEL_NEOO];

/* Gain already baked into eoo_v2; exposed for reference / tests. */
extern const float tx2_model_pilot_gain_eoo_v2;

#ifdef __cplusplus
}
#endif

#endif /* TX2_MODEL_DATA_H */
